require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/timesheets", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Timesheet. As you add validations to Timesheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      company: "MTN",
      date: "2019-08-01",
      start_time: "09:00",
      end_time: "17:00"
    }
  }

  let(:invalid_attributes) {
    {
      company: "",
      date: "invalid date",
      start_time: "not-a-time",
      end_time: "not-a-time"
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # TimesheetsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      @timesheet = create(:timesheet)
      get timesheets_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      timesheet = create(:timesheet, valid_attributes)
      get timesheet_url(timesheet), as: :json
      expect(response).to be_successful
      parsed_json = JSON.parse(response.body)
      expect(parsed_json['company']).to eq(timesheet.company)
      expect(parsed_json['date']).to eq(timesheet.date.strftime("%Y-%m-%d"))
      expect(parsed_json['start_time']).to eq(timesheet.start_time.strftime("%H:%M"))
      expect(parsed_json['end_time']).to eq(timesheet.end_time.strftime("%H:%M"))
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Timesheet" do
        @employee = create(:employee)
        valid_attributes['employee_id'] = @employee.id

        expect {
          post timesheets_url,
               params: { timesheet: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Timesheet, :count).by(1)
      end

      it "renders a JSON response with the new timesheet" do
        @employee = create(:employee)
        valid_attributes['employee_id'] = @employee.id
        post timesheets_url,
             params: { timesheet: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Timesheet" do
        expect {
          post timesheets_url,
               params: { timesheet: invalid_attributes }, as: :json
        }.to change(Timesheet, :count).by(0)
      end

      it "renders a JSON response with errors for the new timesheet" do
        post timesheets_url,
             params: { timesheet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
      
      it "does not create a new Timesheet for invalid date" do
        invalid_attributes['date'] = "Invalid Date"
        expect {
          post timesheets_url,
               params: { timesheet: invalid_attributes }, as: :json
        }.to change(Timesheet, :count).by(0)
      end

      it "does not create a new Timesheet for invalid start_time" do
        invalid_attributes['start_time'] = "Invalid Time"
        expect {
          post timesheets_url,
               params: { timesheet: invalid_attributes }, as: :json
        }.to change(Timesheet, :count).by(0)
      end

      it "does not create a new Timesheet for invalid end_time" do
        invalid_attributes['end_time'] = "Invalid Time"
        expect {
          post timesheets_url,
               params: { timesheet: invalid_attributes }, as: :json
        }.to change(Timesheet, :count).by(0)
      end

      it "does not create a new Timesheet for end_time before start_time" do
        invalid_attributes['end_time'] = "09:00"
        invalid_attributes['start_time'] = "10:00"
        expect {
          post timesheets_url,
               params: { timesheet: invalid_attributes }, as: :json
        }.to change(Timesheet, :count).by(0)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          company: "Vodafone",
          date: "2019-08-02",
          start_time: "10:00",
          end_time: "18:00"
        }
      }

      it "updates the requested timesheet" do
        timesheet = create(:timesheet, valid_attributes)
        patch timesheet_url(timesheet),
              params: { timesheet: new_attributes }, headers: valid_headers, as: :json
        timesheet.reload
        
        parsed_json = JSON.parse(response.body)
        expect(parsed_json[:company]).to eq(new_attributes['company'])
        expect(parsed_json[:date]).to eq(new_attributes['date'])
        expect(parsed_json[:start_time]).to eq(new_attributes['start_time'])
        expect(parsed_json[:end_time]).to eq(new_attributes['end_time'])
      end

      it "renders a JSON response with the timesheet" do
        timesheet = create(:timesheet, valid_attributes)
        patch timesheet_url(timesheet),
              params: { timesheet: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the timesheet" do
        timesheet = create(:timesheet, valid_attributes)
        patch timesheet_url(timesheet),
              params: { timesheet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested timesheet" do
      timesheet = create(:timesheet, valid_attributes)
      expect {
        delete timesheet_url(timesheet), headers: valid_headers, as: :json
      }.to change(Timesheet, :count).by(-1)
    end
  end
end
